version: 0.2
phases:
  pre_build:
    commands:
      - echo "Hello there and here"
      - echo "Deploying with Github"
 
  build:
    commands:
      - pwd
      - echo WEBSITE_BUCKET_NAME
      - aws s3 cp index.html s3://WEBSITE_BUCKET_NAME/
